//
// Generated file, do not edit! Created by nedtool 4.6 from NetPkt.msg.
//

#ifndef _NETPKT_M_H_
#define _NETPKT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>NetPkt.msg:14</tt> by nedtool.
 * <pre>
 * //
 * // Packet type that can be relayed by a Cloud.
 * //
 * packet NetPkt
 * {
 *     int srcAddress;
 *     int destAddress;
 * }
 * </pre>
 */
class NetPkt : public ::cPacket
{
  protected:
    int srcAddress_var;
    int destAddress_var;

  private:
    void copy(const NetPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NetPkt&);

  public:
    NetPkt(const char *name=NULL, int kind=0);
    NetPkt(const NetPkt& other);
    virtual ~NetPkt();
    NetPkt& operator=(const NetPkt& other);
    virtual NetPkt *dup() const {return new NetPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);
};

inline void doPacking(cCommBuffer *b, NetPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, NetPkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef _NETPKT_M_H_

